/** USER ACTIONS **/
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';

/** AUTHENTICATION **/
export const LOGIN_GOOGLE_REQUEST = 'LOGIN_GOOGLE_REQUEST';

/** MODAL ACTIONS **/
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

/** USER PERMISSION STATUSES **/
export const ANONYMOUS = 'ANONYMOUS';
export const PENDING = 'PENDING';
export const CUSTOMER = 'CUSTOMER';
export const SELLER = 'SELLER';
export const ADMIN = 'ADMIN';

/** PRODUCTS */
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';

/** ROW EXPANSION **/
export const TOGGLE_SHOW_DESCRIPTION = 'TOGGLE_SHOW_DESCRIPTION';

/** PRICE UPDATES **/
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';